### ISSUE TITLE
Additional meta-data in the YAML

### ISSUE THREAD

**Issue by OmenWild** [ucdavis/hippo#190]
We need additional meta-data in the YAML files under a new `meta:` section.

Include the cluster name: 
`cluster: farm`

Include the operation, for example:
`operation: ssh-key-change`
`operation: new-sponsor`
`operation: remove-sponsor` # for a future feature where a PI can un-sponsor a user

```yaml
meta:
  cluster: farm
  operation: ssh-key-change
```
