### ISSUE TITLE
URGENT: Erroneous Values for `sponsor::cluster`

### ISSUE THREAD

**Issue by camillescottatwork** [ucdavis/hippo#206]
The YAML is still sometimes returning erroneous values for `account::cluster`. For example, one just came in that looks like:

```yaml
sponsor:
  accountname: Timothy Hanks
  name: Timothy Hanks
  email: ############
  kerb: thanks
  iam: ###########
  mothra: #########
  cluster: &o1
    Id: 7
    Name: Franklin
    Description: Franklin cluster for the College of Biological Sciences (MCB, MMG, CNS,  PLB)
    SshName: hippo-user
    SshKeyId: ##########33
    SshUrl: franklin.hpc.ucdavis.edu
    IsActive: true
    Accounts:
    - &o0
      Id: 108
      CreatedOn: 2023-06-06T21:57:42.3778128
      UpdatedOn: 2023-06-06T21:57:42.3778129
      CanSponsor: true
      IsAdmin: false
      Name: Timothy Hanks
      IsActive: true
      SshKey: 
      Status: Active
      OwnerId: 152
      Owner:
        Id: 152
        FirstName: Timothy
        LastName: Hanks
        Email: ###########
        Iam: #########3
        Kerberos: thanks
        MothraId: #############
        Accounts:
        - *o0
        Name: Timothy Hanks
        IsAdmin: false
      SponsorId: 
      Sponsor: 
      ClusterId: 7
      Cluster: *o1
      Histories: []
```
